version: '3'

services:
  docker-container-registry:
    container_name: docker-container-registry
    image: registry:2.8.3
    restart: always
    labels:
      app: dcr
    ports:
      - "5000:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - dcr-auth:/auth
      - dcr-images:/data

volumes:
  dcr-images:
    labels:
      app: dcr
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./images
  dcr-auth:
    labels:
      app: dcr
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./auth

networks:
  dcr:
    labels:
      app: dcr
